import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'
import SubscribeSection from '@/components/layout/subscribeSection'
import { ToastContainer } from 'react-toastify'
import { InitAuth } from '@/components/init-auth'

const inter = Inter({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Cooking app',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className='h-screen'>
            <body
                className={`${inter.className} antialiased h-screen flex  flex-col`}
            >
                <ToastContainer />
                <Header />
                <InitAuth />
                <main className='flex-1 px-20 max-lg:px-5 max-sm:px-0 relative'>
                    {children}
                </main>
                <div className='px-20 max-lg:px-5'>
                    <SubscribeSection />
                </div>
                <Footer />
            </body>
        </html>
    )
}
