import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'

const inter = Inter({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className='h-screen'>
            <body
                className={`${inter.className} antialiased h-screen flex  flex-col`}
            >
                <Header />
                <main className='flex-1 px-20 max-lg:px-5 max-sm:px-0'>
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    )
}
